#!/bin/sh
### BEGIN INIT INFO
# Provides:		mullvad-early-boot-blocking
# Required-Start:	mullvad-daemon
# Required-Stop:
# Should-Start:
# Should-Stop:
# X-Start-Before:
# X-Stop-After:
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Description:		Mullvad early boot network blocker
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
COMMAND="/usr/bin/mullvad-daemon"
COMMAND_ARGS="--initialize-early-boot-firewall"
DESC="Mullvad early boot network blocker"
SCRIPTNAME=/etc/init.d/mullvad-early-boot-blocking

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

# Exit if the package is not installed
test -x $COMMAND || exit 0

case "$1" in
	start)
		log_daemon_msg "Starting $DESC" "$NAME"
		$COMMAND $COMMAND_ARGS
		log_end_msg $?
		;;
	*)
		echo "Usage: $SCRIPTNAME start" >&2
		exit 3
		;;
esac	
