#!/bin/sh
### BEGIN INIT INFO
# Provides:		mullvad-daemon
# Required-Start:	$network
# Required-Stop:	$network
# Should-Start:
# Should-Stop:
# X-Start-Before:
# X-Stop-After:
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Description:		Mullvad VPN daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON="/usr/bin/mullvad-daemon"
DAEMON_ARGS="-v --disable-stdout-timestamps"
NAME=mullvad-daemon
DESC="Mullvad VPN daemon"
SCRIPTNAME=/etc/init.d/mullvad-daemon
PIDFILE=/run/mullvad-daemon/$NAME.pid
MULLVAD_RESOURCE_DIR="/opt/Mullvad VPN/resources/"

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

# Exit if the package is not installed
test -x $DAEMON || exit 0

case "$1" in
	start)
		log_daemon_msg "Starting $DESC" "$NAME"
		mkdir -p `dirname "$PIDFILE"`
		start-stop-daemon --start --background --make-pidfile --quiet --oknodo --pidfile "$PIDFILE" --exec $DAEMON -- $DAEMON_ARGS
		log_end_msg $?
		;;
	stop)
		log_daemon_msg "Stopping $DESC" "$NAME"
		start-stop-daemon --stop --remove-pidfile --quiet --retry 5 --oknodo --pidfile $PIDFILE --name $NAME
		status=$?
		log_end_msg $status
		;;
	reload|force-reload)
		log_daemon_msg "Reloading $DESC" "$NAME"
		start-stop-daemon --stop --quiet --pidfile $PIDFILE --name $NAME --signal 1
		status=$?
		log_end_msg $status
		;;
	restart)
		log_daemon_msg "Restarting $DESC" "$NAME"
		if start-stop-daemon --stop --remove-pidfile --quiet --retry 5 --oknodo --pidfile $PIDFILE --name $NAME; then
			start-stop-daemon --start --background --make-pidfile --quiet --pidfile "$PIDFILE" --exec $DAEMON -- $DAEMON_ARGS
		fi
		status=$?
		log_end_msg $status
		;;
	status)
		status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME" && exit 0 || exit $?
		;;
	*)
		echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status}" >&2
		exit 3
		;;
esac

